int32 throttleMode
float64 throttle
float64 Target_deceleration
int32 brakeMode
float64 brake
int32 steeringMode
float64 wheelAngle
bool handbrake
bool isManualGear
int32  gear
float64 clutch
int32 Auto_Left_Turn_Light_Command 
int32 Auto_Right_Turn_Light_Command 
int32 Auto_EPB_Enable 
int32 Auto_car_hopper

float64 AccPedal_per
int32 Acc_activate_Status
int32 Acc_activate
int32 Acc_checksum
int32 Acc_count

float64 BrakeDecel
int32 Decel_activate_Status
int32 Decel_checksum
int32 Decel_count

int32 EleHandbrakeStatus
int32 Ele_activate_Status
int32 Ele_checksum
int32 Ele_count

float64 Retarder_per
int32 Retarder_activate
int32 Retarder_checksum
int32 Retarder_count

float64 Curvature_command
float64 steer_control
int32 steer_activate
int32 steer_checksum
int32 steer_count
int32 steercontrol_model

int32 GearCommand       #    D = 1，    N = 0，     R = -1，     P = -2
int32 GearHighest
int32 gear_activate
int32 gear_checksum
int32 gear_count

int32 bucket_command
int32 bucket_activate
int32 bucket_checksum
int32 bucket_count
int32 bucketspeed_model

int32 light_left
int32 light_right
int32 light_near
int32 light_far
int32 light_rotating
int32 light_air
int32 light_frontfog
int32 light_frontwork
int32 light_sidemarker
int32 light_station
int32 light_hazard
int32 light_backwork
int32 differntial_solenoid_valve
int32 exhaust_brake_output
int32 radiator_fan
int32 windshieldwiper
int32 kettle

int32 vehicle_load

int32 on_off
int32 set_temperature
int32 demisting
int32 workmodel
int32 drought_model
int32 setWind_speed


