// Generated by gencpp from file msg_gen/Gps.msg
// DO NOT EDIT!


#ifndef MSG_GEN_MESSAGE_GPS_H
#define MSG_GEN_MESSAGE_GPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace msg_gen
{
template <class ContainerAllocator>
struct Gps_
{
  typedef Gps_<ContainerAllocator> Type;

  Gps_()
    : header()
    , gps_time(0)
    , state(false)
    , lat(0.0)
    , lon(0.0)
    , posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , Rear_posX(0.0)
    , Rear_posY(0.0)
    , Rear_posZ(0.0)
    , oriX(0.0)
    , oriY(0.0)
    , oriZ(0.0)
    , velX(0.0)
    , velY(0.0)
    , velZ(0.0)
    , speed(0.0)
    , accelX(0.0)
    , accelY(0.0)
    , accelZ(0.0)
    , angVelX(0.0)
    , angVelY(0.0)
    , angVelZ(0.0)  {
    }
  Gps_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gps_time(0)
    , state(false)
    , lat(0.0)
    , lon(0.0)
    , posX(0.0)
    , posY(0.0)
    , posZ(0.0)
    , Rear_posX(0.0)
    , Rear_posY(0.0)
    , Rear_posZ(0.0)
    , oriX(0.0)
    , oriY(0.0)
    , oriZ(0.0)
    , velX(0.0)
    , velY(0.0)
    , velZ(0.0)
    , speed(0.0)
    , accelX(0.0)
    , accelY(0.0)
    , accelZ(0.0)
    , angVelX(0.0)
    , angVelY(0.0)
    , angVelZ(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _gps_time_type;
  _gps_time_type gps_time;

   typedef uint8_t _state_type;
  _state_type state;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _posX_type;
  _posX_type posX;

   typedef double _posY_type;
  _posY_type posY;

   typedef double _posZ_type;
  _posZ_type posZ;

   typedef double _Rear_posX_type;
  _Rear_posX_type Rear_posX;

   typedef double _Rear_posY_type;
  _Rear_posY_type Rear_posY;

   typedef double _Rear_posZ_type;
  _Rear_posZ_type Rear_posZ;

   typedef double _oriX_type;
  _oriX_type oriX;

   typedef double _oriY_type;
  _oriY_type oriY;

   typedef double _oriZ_type;
  _oriZ_type oriZ;

   typedef double _velX_type;
  _velX_type velX;

   typedef double _velY_type;
  _velY_type velY;

   typedef double _velZ_type;
  _velZ_type velZ;

   typedef double _speed_type;
  _speed_type speed;

   typedef double _accelX_type;
  _accelX_type accelX;

   typedef double _accelY_type;
  _accelY_type accelY;

   typedef double _accelZ_type;
  _accelZ_type accelZ;

   typedef double _angVelX_type;
  _angVelX_type angVelX;

   typedef double _angVelY_type;
  _angVelY_type angVelY;

   typedef double _angVelZ_type;
  _angVelZ_type angVelZ;





  typedef boost::shared_ptr< ::msg_gen::Gps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg_gen::Gps_<ContainerAllocator> const> ConstPtr;

}; // struct Gps_

typedef ::msg_gen::Gps_<std::allocator<void> > Gps;

typedef boost::shared_ptr< ::msg_gen::Gps > GpsPtr;
typedef boost::shared_ptr< ::msg_gen::Gps const> GpsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg_gen::Gps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg_gen::Gps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::msg_gen::Gps_<ContainerAllocator1> & lhs, const ::msg_gen::Gps_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gps_time == rhs.gps_time &&
    lhs.state == rhs.state &&
    lhs.lat == rhs.lat &&
    lhs.lon == rhs.lon &&
    lhs.posX == rhs.posX &&
    lhs.posY == rhs.posY &&
    lhs.posZ == rhs.posZ &&
    lhs.Rear_posX == rhs.Rear_posX &&
    lhs.Rear_posY == rhs.Rear_posY &&
    lhs.Rear_posZ == rhs.Rear_posZ &&
    lhs.oriX == rhs.oriX &&
    lhs.oriY == rhs.oriY &&
    lhs.oriZ == rhs.oriZ &&
    lhs.velX == rhs.velX &&
    lhs.velY == rhs.velY &&
    lhs.velZ == rhs.velZ &&
    lhs.speed == rhs.speed &&
    lhs.accelX == rhs.accelX &&
    lhs.accelY == rhs.accelY &&
    lhs.accelZ == rhs.accelZ &&
    lhs.angVelX == rhs.angVelX &&
    lhs.angVelY == rhs.angVelY &&
    lhs.angVelZ == rhs.angVelZ;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::msg_gen::Gps_<ContainerAllocator1> & lhs, const ::msg_gen::Gps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace msg_gen

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::msg_gen::Gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg_gen::Gps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::Gps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg_gen::Gps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::Gps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg_gen::Gps_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg_gen::Gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2bc2c5286b867f56113985f53f9fe507";
  }

  static const char* value(const ::msg_gen::Gps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2bc2c5286b867f56ULL;
  static const uint64_t static_value2 = 0x113985f53f9fe507ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg_gen::Gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg_gen/Gps";
  }

  static const char* value(const ::msg_gen::Gps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg_gen::Gps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"int32 gps_time\n"
"bool state\n"
"float64 lat\n"
"float64 lon\n"
"float64 posX\n"
"float64 posY\n"
"float64 posZ\n"
"float64 Rear_posX\n"
"float64 Rear_posY\n"
"float64 Rear_posZ\n"
"float64 oriX    #roll\n"
"float64 oriY    #pitch\n"
"float64 oriZ    #yaw\n"
"float64 velX\n"
"float64 velY\n"
"float64 velZ\n"
"float64 speed\n"
"float64 accelX\n"
"float64 accelY\n"
"float64 accelZ\n"
"float64 angVelX\n"
"float64 angVelY\n"
"float64 angVelZ\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::msg_gen::Gps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg_gen::Gps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gps_time);
      stream.next(m.state);
      stream.next(m.lat);
      stream.next(m.lon);
      stream.next(m.posX);
      stream.next(m.posY);
      stream.next(m.posZ);
      stream.next(m.Rear_posX);
      stream.next(m.Rear_posY);
      stream.next(m.Rear_posZ);
      stream.next(m.oriX);
      stream.next(m.oriY);
      stream.next(m.oriZ);
      stream.next(m.velX);
      stream.next(m.velY);
      stream.next(m.velZ);
      stream.next(m.speed);
      stream.next(m.accelX);
      stream.next(m.accelY);
      stream.next(m.accelZ);
      stream.next(m.angVelX);
      stream.next(m.angVelY);
      stream.next(m.angVelZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg_gen::Gps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg_gen::Gps_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "gps_time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gps_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "posX: ";
    Printer<double>::stream(s, indent + "  ", v.posX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "posY: ";
    Printer<double>::stream(s, indent + "  ", v.posY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "posZ: ";
    Printer<double>::stream(s, indent + "  ", v.posZ);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Rear_posX: ";
    Printer<double>::stream(s, indent + "  ", v.Rear_posX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Rear_posY: ";
    Printer<double>::stream(s, indent + "  ", v.Rear_posY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "Rear_posZ: ";
    Printer<double>::stream(s, indent + "  ", v.Rear_posZ);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "oriX: ";
    Printer<double>::stream(s, indent + "  ", v.oriX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "oriY: ";
    Printer<double>::stream(s, indent + "  ", v.oriY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "oriZ: ";
    Printer<double>::stream(s, indent + "  ", v.oriZ);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velX: ";
    Printer<double>::stream(s, indent + "  ", v.velX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velY: ";
    Printer<double>::stream(s, indent + "  ", v.velY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "velZ: ";
    Printer<double>::stream(s, indent + "  ", v.velZ);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accelX: ";
    Printer<double>::stream(s, indent + "  ", v.accelX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accelY: ";
    Printer<double>::stream(s, indent + "  ", v.accelY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "accelZ: ";
    Printer<double>::stream(s, indent + "  ", v.accelZ);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angVelX: ";
    Printer<double>::stream(s, indent + "  ", v.angVelX);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angVelY: ";
    Printer<double>::stream(s, indent + "  ", v.angVelY);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "angVelZ: ";
    Printer<double>::stream(s, indent + "  ", v.angVelZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_GEN_MESSAGE_GPS_H
