bool LinkState			#1830FF21
int8 Car_Control_Mode		#1830B021
int8 EstopState			#1830B021
int8 Gas_pedal_TakeOver		#1830E621
int8 EPB_TakeOver			#1830E621
int8 Steer_TakeOver			#1830E621
int8 EPB_Parking_State		#0C301421
int16 A2M_TakeOver			#todo
int8 current_Gear			#0C303021
float64 Engine_torque_percentage	#0C300021
float64 Engine_rpm			#0C300021
float64 Gas_pedal_percentage		#0C300021
float64 Gas_pedal_percentage_actual	#0C300021
float64 Break_pedal_percentage	#0C301021
float64 retarder_torque_percentage	#0C301221
float64 wheel_angle			#0C302121
float64 Speed_byGear		#0C303021
float64 Lifting_Angle		#0C304021
bool Engine_Flameout
time ToControl_time
